wandb:
  project: default
  name: ''
  enable: False

debug: false
datapath: /work/log1/chendi.qian/qp_400_new
runs: 1
losstype: l2
ckpt: false
lr: 1.e-3
weight_decay: 0.
epoch: 1000
patience: 200
batchsize: 128
train_frac: 1.

backbone:
  conv: sageconv
  hidden: 128
  num_encode_layers: 3
  num_conv_layers: 3
  num_mlp_layers: 1
  num_pred_layers: 2
  norm: graphnorm

data_aug:
  method:
    AddRedundantConstraint:
      strength: 0.5
      affinity: 3
    ScaleConstraint:
      strength: 1.

  drop_rate: 0.5

num_pred_layers: 1