wandb:
  project: default
  name: ''
  enable: False

debug: false
modelpath: ./pretrained/best_model0.pt
datapath: /work/log1/chendi.qian/qp_400_new
runs: 1
losstype: l2
ckpt: true
lr: 1.e-3
weight_decay: 0.
epoch: 1000
patience: 100
batchsize: 32
val_batchsize: 128
train_whole: false
train_frac: 0.01

eval_every: 1
conv: gcnconv
hidden: 128
num_encode_layers: 2
num_conv_layers: 8
num_pred_layers: 2
num_mlp_layers: 1
norm: graphnorm