finetune:
  modelpath: null
  whole: true

pretrain:
  epoch: 500
  method:
    GraphCLDropNode:
      strength: 0.47
    GraphCLPerturbEdge:
      strength: 0.32
    GraphCLMaskNode:
      strength: 0.12

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - default_pretrain
  - _self_