finetune:
  modelpath: null
  whole: true

pretrain:
  epoch: 200
  method:
    GraphCLDropNode:
      strength: 0.2
    GraphCLPerturbEdge:
      strength: 0.15
    GraphCLMaskNode:
      strength: 0.2

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - default_pretrain
  - _self_