finetune:
  modelpath: null
  whole: true

pretrain:
  method:
    GraphCLDropNode:
      strength: 0.3
    GraphCLPerturbEdge:
      strength: 0.
    GraphCLMaskNode:
      strength: 0

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - default_pretrain
  - _self_