finetune:
  modelpath: null
  whole: true

pretrain:
  method:
    # this is the only augmentation
    PageRankAugment:
      strength: 0.5

  num_pred_layers: 2  # this is fixed

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - default_pretrain
  - _self_