program: run.py
method: bayes
project: main_50_100
run_cap: 30
entity: chendiqian

metric:
  goal: minimize
  name: test_obj_gap_mean
parameters:
  wandb.enable:
    value: true

  debug:
    value: false
  datapath:
    value: /work/log1/chendi.qian/ssl/gen_50_100_0.1
  runs:
    value: 3
  losstype:
    value: l2
  ckpt:
    value: false

  lr:
    values: [1.e-4, 1.e-3]
  weight_decay:
    value: 0.
  epoch:
    value: 1000
  patience:
    value: 100
  batchsize:
    values: [128, 256, 512]
  train_frac:
    value: 1.

  backbone.conv:
    value: gcnconv
  backbone.hidden:
    value: 128
  backbone.num_encode_layers:
    values: [1, 2, 3]
  backbone.num_conv_layers:
    values: [2, 3, 4]
  backbone.num_pred_layers:
    values: [2, 3]
  backbone.num_mlp_layers:
    value: 1  # for mlp in conv
  backbone.norm:
    value: graphnorm

  num_pred_layers:
    value: 1

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}