program: run.py
method: bayes
project: main_100_200
run_cap: 30
entity: chendiqian

metric:
  goal: minimize
  name: best_val_obj_gap
parameters:
  wandb.enable:
    value: true

  debug:
    value: false
  datapath:
    value: /work/log1/chendi.qian/ssl/gen_100200_100200_0.05
  runs:
    value: 1
  losstype:
    value: l2
  ckpt:
    value: false

  lr:
    value: 1.e-3
  weight_decay:
    value: 0.
  epoch:
    value: 1000
  patience:
    value: 100
  batchsize:
    value: 128
  train_frac:
    value: 1.

  backbone.conv:
    value: sageconv
  backbone.hidden:
    values: [128, 256, 192]
  backbone.num_encode_layers:
    values: [2, 3]
  backbone.num_conv_layers:
    values: [3, 4, 5, 6, 8]
  backbone.num_pred_layers:
    values: [2, 3]
  backbone.num_mlp_layers:
    value: 1  # for mlp in conv
  backbone.norm:
    value: graphnorm

  num_pred_layers:
    value: 1

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}