finetune:
  modelpath: null
  whole: true

pretrain:
  method:
    # this is the only augmentation
    PageRankAugment:
      strength: 0.5

  num_pred_layers: 1  # this is fixed, see https://github.com/PyGCL/PyGCL/blob/main/examples/MVGRL_graph.py#L127

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - default_pretrain
  - _self_