finetune:
  modelpath: null
  whole: true
  folds: 10

pretrain:
  epoch: 800
  method:
    ScaleConstraint:
      strength: 1.
    ScaleCoordinate:
      strength: 1.
    AddRedundantConstraint:
      strength: 0.06
      affinity: 3
    AddDumbVariables:
      strength: 0.38

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - default_pretrain
  - _self_