wandb:
  project: default
  name: ''
  enable: False

debug: false
datapath: /work/log1/chendi.qian/ssl/gen_50_100_0.1
runs: 1
losstype: l2
ckpt: false

backbone:
  conv: customconv
  hidden: 128
  num_encode_layers: 3
  num_conv_layers: 3
  num_mlp_layers: 1
  num_pred_layers: 2
  norm: graphnorm

finetune:
  lr: 1.e-4
  weight_decay: 0.
  epoch: 1000
  patience: 200
  batchsize: 128
  train_frac: 0.01
  modelpath: null
  whole: true
  num_pred_layers: 1

pretrain:
  negatives: 4
  method: "32"
  lr: 1.e-3
  weight_decay: 0.
  epoch: 200
  patience: 50
  batchsize: 256
  drop_rate: 0.2
  temperature: 0.1
  num_pred_layers: 0  # no projector