finetune:
  lr: 1.e-3
  weight_decay: 0.
  epoch: 1000
  patience: 200
  batchsize: 128
  train_frac: 0.01
  modelpath: null
  whole: true
  num_pred_layers: 1

pretrain:
  method:
    DropInactiveConstraint:
      strength: 0.3
      temperature: 1.
#    OracleDropInactiveConstraint:
#      strength: 0.
    ScaleConstraint:
      strength: 1.
#    ScaleObj:
#      strength: 0.
    ScaleCoordinate:
      strength: 1.
    AddRedundantConstraint:
      strength: 0.3
      affinity: 3
    AddSubOrthogonalConstraint:
      strength: 0.3
    AddDumbVariables:
      strength: 0.3

  lr: 1.e-3
  weight_decay: 0.
  epoch: 200
  patience: 50
  batchsize: 256
  temperature: 0.1
  num_pred_layers: 0  # no projector

defaults:
  - defaults