finetune:
  modelpath: null
  whole: true

pretrain:
  method:
    DropInactiveConstraint:
      strength: 0.1
      temperature: 1.
#    OracleDropInactiveConstraint:
#      strength: 0.
    ScaleConstraint:
      strength: 1.
#    ScaleObj:
#      strength: 0.
    ScaleCoordinate:
      strength: 1.
    AddRedundantConstraint:
      strength: 0.3
      affinity: 3
    AddSubOrthogonalConstraint:
      strength: 0.3
    AddDumbVariables:
      strength: 0.3

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - default_pretrain
  - _self_