finetune:
  modelpath: null
  whole: true
  folds: 10

pretrain:
  epoch: 1000
  method:
    DropInactiveConstraint:
      strength: 0.1
    ScaleConstraint:
      strength: 1.
    ScaleCoordinate:
      strength: 1.
    AddRedundantConstraint:
      strength: 0.4
      affinity: 3
    AddDumbVariables:
      strength: 0.2

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - default_pretrain
  - _self_