wandb:
  project: default
  name: ''
  enable: False

debug: false
runs: 1
losstype: l1
ckpt: true
lr: 1.e-3
weight_decay: 0.
epoch: 1000
patience: 100
batchsize: 128
train_frac: 1.

conv: ginconv
hidden: 192
num_conv_layers: 5
num_pred_layers: 1
num_mlp_layers: 1
num_backbone_mlp: 2
norm: graphnorm