finetune:
  folds: 1
  train_frac: 1.
  batchsize: 1
  patience: 50

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - _self_
  # If you want your primary config to override the values of configs from the Defaults List,
  # append _self_ to the end of the Defaults List.