data_aug:
  num_samples: 2
  method:
    OracleDropIdleVariable:
      strength: 0.
    OracleDropInactiveConstraint:
      strength: 0.5
    ScaleConstraint:
      strength: 0.5
    ScaleCoordinate:
      strength: 0.5
    AddRedundantConstraint:
      strength: 0.6
      affinity: 3
    AddDumbVariables:
      strength: 0.

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - _self_