data_aug:
  method:
    AddRedundantConstraint:
      strength: 0.5
      affinity: 3
    ScaleConstraint:
      strength: 1.
    # We should make full use of the labels
    OracleDropInactiveConstraint:
      strength: 0.3


defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - _self_