data_aug:
  num_samples: 3
  method:
    OracleDropInactiveConstraint:
      strength: 0.5
    ScaleConstraint:
      strength: 0.5
    ScaleCoordinate:
      strength: 0.5
    AddRedundantConstraint:
      strength: 0.6
      affinity: 3
#    AddSubOrthogonalConstraint:
#      strength: 0.
    AddDumbVariables:
      strength: 0.

defaults:
  - default_exp
  - default_backbone
  - default_finetune
  - _self_