program: run.py
method: bayes
project: sweep_qp_combo
run_cap: 20
entity: chendiqian

metric:
  goal: minimize
  name: best_val_obj_gap
parameters:
  wandb.enable:
    value: true

  exp.debug:
    value: false
  exp.datapath:
    value: /work/log1/chendi.qian/ssl/qp_100_100_0.05_0.05
  exp.runs:
    value: 1
  exp.ckpt:
    value: false

  finetune.lr:
    value: 1.e-3
  finetune.weight_decay:
    value: 0.
  finetune.epoch:
    value: 2000
  finetune.patience:
    value: 200
  finetune.batchsize:
    value: 32
  finetune.train_frac:
    value: 0.2
  finetune.num_pred_layers:
    value: 1
  finetune.folds:
    value: 3

  backbone.conv:
    value: sageconv
  backbone.hidden:
    value: 192
  backbone.num_encode_layers:
    value: 2
  backbone.num_conv_layers:
    value: 6
  backbone.num_pred_layers:
    value: 3
  backbone.num_mlp_layers:
    value: 1  # for mlp in conv
  backbone.norm:
    value: graphnorm

  data_aug.method.OracleDropInactiveConstraint.strength:
    values: [ 0.5, 0.99 ]  # 0.5
  data_aug.method.ScaleConstraint.strength:
    values: [ 0.5, 1. ]
  data_aug.method.ScaleCoordinate.strength:
    values: [ 0.5, 1. ]
  data_aug.method.AddRedundantConstraint.strength:
    values: [ 0., 0.2, 0.4, 0.6 ]   # 0.4
  data_aug.method.AddDumbVariables.strength:
    values: [ 0., 0.2, 0.4, 0.6 ]   # 0.4
  data_aug.num_samples:
    values: [1, 2, 3]

command:
  - ${env}
  - python
  - ${program}
#  - --config-name
#  - su_aug_addv
  - ${args_no_hyphens}
